import { createActions } from "redux-actions";

export const companyTypes = {
//公司列表
COMPANYWEBLIST:"COMPANYWEBLIST",
COMPANYWEBLIST_SUCCESS:"COMPANYWEBLIST_SUCCESS",
//公司详情
COMPANYDETAILWEB:"COMPANYDETAILWEB",
COMPANYDETAILWEB_SUCCESS:"COMPANYDETAILWEB_SUCCESS",
//公司操作-基本信息,对接人信息
GETBASICCOMPANY:"GETBASICCOMPANY",
GETBASICCOMPANY_SUCCESS:"GETBASICCOMPANY_SUCCESS",
//公司操作记录
GETCOMPANYOPERATERECORD:"GETCOMPANYOPERATERECORD",
GETCOMPANYOPERATERECORD_SUCCESS:"GETCOMPANYOPERATERECORD_SUCCESS",
//头部返回信息
COMPANYOPERATEDETAIL:"COMPANYOPERATEDETAIL",
COMPANYOPERATEDETAIL_SUCCESS:"COMPANYOPERATEDETAIL_SUCCESS",
//审核通过
COMPANYOPERATEPASS:"COMPANYOPERATEPASS",
COMPANYOPERATEPASS_SUCCESS:"COMPANYOPERATEPASS_SUCCESS",
//审核不通过
COMPANYOPERATENOPASS:"COMPANYOPERATENOPASS",
COMPANYOPERATENOPASS_SUCCESS:"COMPANYOPERATENOPASS_SUCCESS",
//资料补全信息
GETCOMPLETEDATA:"GETCOMPLETEDATA",
GETCOMPLETEDATA_SUCCESS:"GETCOMPLETEDATA_SUCCESS",
//复审-通过
COMPANYREVIEWOPERATEPASS:"COMPANYREVIEWOPERATEPASS",
COMPANYREVIEWOPERATEPASS_SUCCESS:"COMPANYREVIEWOPERATEPASS_SUCCESS",
//复审-不通过
COMPANYREVIEWOPERATENOPASS:"COMPANYREVIEWOPERATENOPASS",
COMPANYREVIEWOPERATENOPASS_SUCCESS:"COMPANYREVIEWOPERATENOPASS_SUCCESS",
//设立
COMPANYOPERATEESTABLISH:"COMPANYOPERATEESTABLISH",
COMPANYOPERATEESTABLISH_SUCCESS:"COMPANYOPERATEESTABLISH_SUCCESS",
//驳回
COMPANYOPERATEREJECT:"COMPANYOPERATEREJECT",
COMPANYOPERATEREJECT_SUCCESS:"COMPANYOPERATEREJECT_SUCCESS",
//锁定
COMPANYOPERATEBILLLOCK:"COMPANYOPERATEBILLLOCK",
COMPANYOPERATEBILLLOCK_SUCCESS:"COMPANYOPERATEBILLLOCK_SUCCESS",
//发消息给客户
SENDNOTICE:"SENDNOTICE",
SENDNOTICE_SUCCESS:"SENDNOTICE_SUCCESS",
//修改对接人信息
UPDATEDOCK:"UPDATEDOCK",
UPDATEDOCK_SUCCESS:"UPDATEDOCK_SUCCESS",

//省市区
GETREGIONBYPID:"GETREGIONBYPID",
GETREGIONBYPID_SUCCESS:"GETREGIONBYPID_SUCCESS",

SGETREGIONBYPID:"SGETREGIONBYPID",
SGETREGIONBYPID_SUCCESS:"SGETREGIONBYPID_SUCCESS",

QGETREGIONBYPID:"QGETREGIONBYPID",
QGETREGIONBYPID_SUCCESS:"QGETREGIONBYPID_SUCCESS",
//法人库列表
LEGALLIST:"LEGALLIST",
LEGALLIST_SUCCESS:"LEGALLIST_SUCCESS",
//法人详情
LEGALDETAIL:"LEGALDETAIL",
LEGALDETAIL_SUCCESS:"LEGALDETAIL_SUCCESS",
// 法人详情下的公司;列表
GETCOMPANYBYLEGALID:"GETCOMPANYBYLEGALID",
GETCOMPANYBYLEGALID_SUCCESS:"GETCOMPANYBYLEGALID_SUCCESS",
//锁定法人
LOCKLEGAL:"LOCKLEGAL",
LOCKLEGAL_SUCCESS:"LOCKLEGAL_SUCCESS",

//名称审核
NAMEEXAMINE:"NAMEEXAMINE",
NAMEEXAMINE_SUCCESS:"NAMEEXAMINE_SUCCESS",

//工商阶段完成
BUSINESSEXAMINE:"BUSINESSEXAMINE",
BUSINESSEXAMINE_SUCCESS:"BUSINESSEXAMINE_SUCCESS",

//银行开户完成
ACCOUNTEXAMINE:"ACCOUNTEXAMINE",
ACCOUNTEXAMINE_SUCCESS:"ACCOUNTEXAMINE_SUCCESS",

//税务认证
TAXEXAMINE:"TAXEXAMINE",
TAXEXAMINE_SUCCESS:"TAXEXAMINE_SUCCESS",

//设立资料选项
GETDATATYPE:"GETDATATYPE",
GETDATATYPE_SUCCESS:"GETDATATYPE_SUCCESS",

//增加上传项
ADDDATATYPE:"ADDDATATYPE",
ADDDATATYPE_SUCCESS:"ADDDATATYPE_SUCCESS",

//勾选//取消
CHECKDATATYPE:"CHECKDATATYPE",
CHECKDATATYPE_SUCCESS:"CHECKDATATYPE_SUCCESS",

//查看上传资料
DATALIST:"DATALIST",
DATALIST_SUCCESS:"DATALIST_SUCCESS",
//一键通知
NOTICE:"NOTICE",
NOTICE_SUCCESS:"NOTICE_SUCCESS",
//工商信息
GETDATA:"GETDATA",
GETDATA_SUCCESS:"GETDATA_SUCCESS",
//更新营业执照
UPDATELICENSE:"UPDATELICENSE",
UPDATELICENSE_SUCCESS:"UPDATELICENSE_SUCCESS",
//发票统计信息
GETINVOICEINFO:"GETINVOICEINFO",
GETINVOICEINFO_SUCCESS:"GETINVOICEINFO_SUCCESS",
//行业下拉
INDUSTRYLIST:"INDUSTRYLIST",
INDUSTRYLIST_SUCCESS:"INDUSTRYLIST_SUCCESS",
//修改公司基本信息
UPDATEBASICCOMPANY:"UPDATEBASICCOMPANY",
UPDATEBASICCOMPANY_SUCCESS:"UPDATEBASICCOMPANY_SUCCESS",
//获取归属人
GETDICTLISTBYVALUE:"GETDICTLISTBYVALUE",
GETDICTLISTBYVALUE_SUCCESS:"GETDICTLISTBYVALUE_SUCCESS",
//获取经办人列表
GETMANAGERLIST:"GETMANAGERLIST",
GETMANAGERLIST_SUCCESS:"GETMANAGERLIST_SUCCESS",
//通知记录
NOTICELIST:"NOTICELIST",
NOTICELIST_SUCCESS:"NOTICELIST_SUCCESS",

//添加信息
UPTBELONGER:"UPTBELONGER",
UPTBELONGER_SUCCESS:"UPTBELONGER_SUCCESS",
//shuju 
GETCOMPANYSTATUSNUM:"GETCOMPANYSTATUSNUM",
GETCOMPANYSTATUSNUM_SUCCESS:"GETCOMPANYSTATUSNUM_SUCCESS",
//工商信息
UPDATEINFO:"UPDATEINFO",
UPDATEINFO_SUCCESS:"UPDATEINFO_SUCCESS",
//经办资料下载
PACKAGEZIP:"PACKAGEZIP",
PACKAGEZIP_SUCCESS:"PACKAGEZIP_SUCCESS"






};

export default createActions({
[companyTypes.COMPANYWEBLIST]: data=> ({data}),
[companyTypes.COMPANYDETAILWEB]: data=> ({data}),
[companyTypes.GETBASICCOMPANY]: data=> ({data}),
[companyTypes.GETCOMPANYOPERATERECORD]: data=> ({data}),
[companyTypes.COMPANYOPERATEDETAIL]: data=> ({data}),
[companyTypes.COMPANYOPERATEPASS]: data=> ({data}),
[companyTypes.COMPANYOPERATENOPASS]: data=> ({data}),
[companyTypes.GETCOMPLETEDATA]: data=> ({data}),
[companyTypes.COMPANYREVIEWOPERATEPASS]: (data,callback)=> ({data,callback}),
[companyTypes.COMPANYREVIEWOPERATENOPASS]: data=> ({data}),
[companyTypes.COMPANYOPERATEESTABLISH]: data=> ({data}),
[companyTypes.COMPANYOPERATEREJECT]: data=> ({data}),
[companyTypes.COMPANYOPERATEBILLLOCK]: data=> ({data}),
[companyTypes.SENDNOTICE]: data=> ({data}),
[companyTypes.UPDATEDOCK]: data=> ({data}),
[companyTypes.GETREGIONBYPID]: data=> ({data}),
[companyTypes.SGETREGIONBYPID]: data=> ({data}),
[companyTypes.QGETREGIONBYPID]: data=> ({data}),
[companyTypes.LEGALLIST]: data=> ({data}),
[companyTypes.LEGALDETAIL]: data=> ({data}),
[companyTypes.GETCOMPANYBYLEGALID]: data=> ({data}),
[companyTypes.LOCKLEGAL]: data=> ({data}),

[companyTypes.NAMEEXAMINE]: data=> ({data}),
[companyTypes.BUSINESSEXAMINE]: data=> ({data}),
[companyTypes.ACCOUNTEXAMINE]: data=> ({data}),
[companyTypes.TAXEXAMINE]: data=> ({data}),
[companyTypes.GETDATATYPE]: data=> ({data}),
[companyTypes.ADDDATATYPE]: data=> ({data}),
[companyTypes.CHECKDATATYPE]: data=> ({data}),
[companyTypes.DATALIST]: data=> ({data}),
[companyTypes.NOTICE]: data=> ({data}),
[companyTypes.GETDATA]: data=> ({data}),
[companyTypes.UPDATELICENSE]: data=> ({data}),
[companyTypes.GETINVOICEINFO]: data=> ({data}),
[companyTypes.INDUSTRYLIST]: data=> ({data}),
[companyTypes.UPDATEBASICCOMPANY]: data=> ({data}),
[companyTypes.GETDICTLISTBYVALUE]: data=> ({data}),
[companyTypes.GETMANAGERLIST]: data=> ({data}),
[companyTypes.NOTICELIST]: data=> ({data}),
[companyTypes.UPTBELONGER]: data=> ({data}),
[companyTypes.GETCOMPANYSTATUSNUM]: data=> ({data}),
[companyTypes.UPDATEINFO]: data=> ({data}),
[companyTypes.PACKAGEZIP]: data=> ({data}),
});


//勾选//取消  CHECKDATATYPE
//UPTBELONGER
//GETCOMPANYSTATUSNUM_SUCCESS

//PACKAGEZIP