import { createActions } from "redux-actions";

export const productTypes = {
//产品列表
PRODUCTLIST:"PRODUCTLIST",
PRODUCTLIST_SUCCESS:"PRODUCTLIST_SUCCESS",
//产品分类列表
PRODUCTCLASSIFY:"PRODUCTCLASSIFY",
PRODUCTCLASSIFY_SUCCESS:"PRODUCTCLASSIFY_SUCCESS",
//产品列表删除
DELETEPRODUCTLIST:"DELETEPRODUCTLIST",
DELETEPRODUCTLIST_SUCCESS:"DELETEPRODUCTLIST_SUCCESS",
//新增产品
ADDPRODUCTLIST:"ADDPRODUCTLIST",
ADDPRODUCTLIST_SUCCESS:"ADDPRODUCTLIST_SUCCESS",
//修改产品
EDITPRODUCTLIST:"EDITPRODUCTLIST",
EDITPRODUCTLIST_SUCCESS:"EDITPRODUCTLIST_SUCCESS",
//开票额度
GETDICTLISTBYTYPE:"GETDICTLISTBYTYPE",
GETDICTLISTBYTYPE_SUCCESS:"GETDICTLISTBYTYPE_SUCCESS",
//编辑分类
UPDATECOMPANYTYPE:"UPDATECOMPANYTYPE",
UPDATECOMPANYTYPE_SUCCESS:"UPDATECOMPANYTYPE_SUCCESS",
//新增分类
ADDCOMPANYTYPE:"ADDCOMPANYTYPE",
ADDCOMPANYTYPE_SUCCESS:"ADDCOMPANYTYPE_SUCCESS",
//删除分类
DELETECOMPANYTYPE:"DELETECOMPANYTYPE",
DELETECOMPANYTYPE_SUCCESS:"DELETECOMPANYTYPE_SUCCESS"
};

export default createActions({
[productTypes.PRODUCTLIST]: data=> ({data}),
[productTypes.PRODUCTCLASSIFY]: data=> ({data}),
[productTypes.DELETEPRODUCTLIST]: data=> ({data}),
[productTypes.ADDPRODUCTLIST]: data=> ({data}),
[productTypes.EDITPRODUCTLIST]: data=> ({data}),
[productTypes.GETDICTLISTBYTYPE]: data=> ({data}),
[productTypes.UPDATECOMPANYTYPE]: data=> ({data}),
[productTypes.ADDCOMPANYTYPE]: data=> ({data}),
[productTypes.DELETECOMPANYTYPE]: data=> ({data}),
});
